print("GESTOR PERDIDAS Y GANANCIAS")
print("--------------------------------")
print("ELije una de las siguientes opciones: ")
print("1. Calcular ganancia")
print("2. Calcular perdida")
print("3. Volver al menu principal")